template: >
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{layout}}" />
    <link rel="stylesheet" href="{{highlight}}">
    <style>
      .markdown-body {
        width: 90%;
        max-width: 700px;
        margin: 20px auto;
      }
    </style>
  </head>
  <body>
    <div class="markdown-body">
      {{fragment}}
    </div>
    <script src="https://unpkg.com/prismjs"></script>
  </body>
  </html>
